---
name: containers-example

instance_groups:
- name: docker
  azs: [z1]
  instances: 1
  persistent_disk: 65536
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: docker
    release: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: "((docker-tls.ca))"
      tls_cert: "((docker-tls.certificate))"
      tls_key: "((docker-tls.private_key))"
  - name: containers
    release: docker
    properties:
      containers:
        - name: redis
          image: "redis"
          command: "--dir /var/lib/redis/ --appendonly yes"
          bind_ports:
            - "6379:6379"
          bind_volumes:
            - "/var/lib/redis"
          entrypoint: "redis-server"
          memory: "256m"
          env_vars:
            - "EXAMPLE_VAR=1"

        - name: mysql
          image: "google/mysql"
          bind_ports:
            - "3306:3306"
          bind_volumes:
            - "/mysql"

        - name: elasticsearch
          image: "bosh/elasticsearch"
          links:
            - mysql:db
          depends_on:
            - mysql
          bind_ports:
            - "9200:9200"
            - "9300:9300"
          bind_volumes:
            - "/data"
          dockerfile: |
            FROM java:7

            RUN \
              cd /tmp && \
              wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.1.tar.gz && \
              tar xvzf elasticsearch-1.1.1.tar.gz && \
              rm -f elasticsearch-1.1.1.tar.gz && \
              mv /tmp/elasticsearch-1.1.1 /elasticsearch

            WORKDIR /data

            CMD ["/elasticsearch/bin/elasticsearch"]

            EXPOSE 9200
            EXPOSE 9300

variables:
- name: docker-ca
  type: certificate
  options:
    is_ca: true
    common_name: dockerCA
- name: docker-tls
  type: certificate
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: docker
  version: 32.6.0
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v32.6.0/docker-32.6.0.tgz
  sha1: 4bf207565f84534f47271a65e2198345f221f0ec
